### ISSUE TITLE
Soulshard datapack not working on spigot (edit Kikipunk)

### ISSUE THREAD

**Issue by lezarius** [kikipunk/SoulShard-DataPack#1]
Im trying to use your datapack and i starting by using them w skeleton... but hell that not work no mob spawning =(

**Comment by kikipunk** [comment]
The spawner display skeleton?
You use vanilla serveur or other?

**Comment by lezarius** [comment]
I use spigot and yes spawner display skeleton (and redstone option)

**Comment by kikipunk** [comment]
Je me permet de vous répondre en français. 
Je viens de faire des test sur spigot, pas moyen de rendre le datapack compatible.

Pour bukkit et c'est dériver il faut exécuter les commande avec "minecraft:" devant mais si je le mes dans un datapack ça me sort des erreur de syntaxe

Désoler, je vais mètre l'info sur curse et planetminecraft en attendant de trouver une solution

**Comment by kikipunk** [comment]
Fix on Paper version

**Comment by lezarius** [comment]
Only on paper ? Or spigot too ?

**Comment by kikipunk** [comment]
Spigot to

**Comment by lezarius** [comment]
Bug persist on spigot =S spawner didn't spawn mobs

**Comment by kikipunk** [comment]
What... Is work on my server. Do you have any plugin ?

**Comment by lezarius** [comment]
Nope... You have discord ? to speak about that i have other datapack of course =S my discord Lezarius#9771
