### ISSUE TITLE
No Zombie Souls due to typo

### ISSUE THREAD

**Issue by dravorle** [kikipunk/SoulShard-DataPack#2]
Greetings, this repository doesn't seem up to date but as I don't have an account on the other websites I'm still using it to convey a little bug:

within /mob/zombie.mcfunction you put:
"advancement revoke @s only soulshard:soulshard/mob/illusioner"

instead of:
"advancement revoke @s only soulshard:soulshard/mob/zombie"

**Comment by kikipunk** [comment]
Thank's sorry for this error i update this, Tomorrow, and I update github code too.

**Comment by dravorle** [comment]
No worries man, glad it reached you!

Great datapack, we're having a blast using it on our server! :)

**Comment by kikipunk** [comment]
fix and update code
