### ISSUE TITLE
Animals Spawned From spawner Dont Give Souls

### ISSUE THREAD

**Issue by rowanplayzYT** [kikipunk/SoulShard-DataPack#4]
I own a Minecraft realm for this data pack and this data pack is pretty awesome! Except that sometimes when i kill mobs from the custom spawner with redstone; doesn't give me souls and other times it does give me souls. But mostly it doesn't, And when i kill naturally generated mobs they always give me souls. So yea. idk.

**Comment by kikipunk** [comment]
It's normal

**Comment by rowanplayzYT** [comment]
oh ok thx
